---
updates:
  - directory: /
    labels:
      - security
    open-pull-requests-limit: 3
    package-ecosystem: docker
    schedule:
      interval: daily
  - directory: /
    labels:
      - security
    open-pull-requests-limit: 3
    package-ecosystem: github-actions
    schedule:
      interval: daily
version: 2
